import type { Firestore, Query } from 'firebase-admin/firestore';
import { FieldValue } from 'firebase-admin/firestore';

import { AuthorizationError, NotFoundError } from '../errors/index.js';
import type { Activity } from '../types/activity.js';
import type { UserId } from '../types/units.js';
import { KgCO2e, UserId as UserIdBrand } from '../types/units.js';
import type { IRepository } from './IRepository.js';

/** Activity creation DTO — id and timestamps generated by repository */
export interface CreateActivityDto {
  readonly input: Activity['input'];
  readonly emissionKg: KgCO2e;
  readonly notes?: string;
}

/** Date range filter for activity queries */
export interface ActivityDateFilter {
  readonly from: Date;
  readonly to: Date;
}

/**
 * Firestore-backed repository for Activity documents.
 * All queries are uid-scoped — cross-user access is impossible by design.
 */
export class ActivityRepository implements IRepository<Activity, CreateActivityDto> {
  private readonly collection = 'activities';

  public constructor(private readonly db: Firestore) {}

  /** @inheritdoc */
  public async findById(id: string): Promise<Activity | null> {
    const doc = await this.db.collection(this.collection).doc(id).get();
    return doc.exists ? this.toEntity(doc.id, doc.data()!) : null;
  }

  /** @inheritdoc */
  public async findByUserId(uid: UserId, limit = 50): Promise<readonly Activity[]> {
    const clampedLimit = Math.min(Math.max(1, limit), 200);
    const snapshot = await this.buildUserQuery(uid)
      .orderBy('timestamp', 'desc')
      .limit(clampedLimit)
      .get();
    return snapshot.docs.map(doc => this.toEntity(doc.id, doc.data()));
  }

  /**
   * Find activities within a date range for a user.
   * Used for weekly/monthly dashboard aggregations.
   */
  public async findByDateRange(
    uid: UserId,
    filter: ActivityDateFilter,
  ): Promise<readonly Activity[]> {
    const snapshot = await this.buildUserQuery(uid)
      .where('timestamp', '>=', filter.from)
      .where('timestamp', '<=', filter.to)
      .orderBy('timestamp', 'desc')
      .get();
    return snapshot.docs.map(doc => this.toEntity(doc.id, doc.data()));
  }

  /** @inheritdoc */
  public async create(uid: UserId, data: CreateActivityDto): Promise<Activity> {
    const docRef = this.db.collection(this.collection).doc();
    const now = new Date();
    const firestoreData = {
      uid,
      input: data.input,
      emissionKg: data.emissionKg,
      notes: data.notes ?? null,
      timestamp: now,
      createdAt: FieldValue.serverTimestamp(),
      deletedAt: null,
    };
    await docRef.set(firestoreData);
    return { id: docRef.id, uid, ...data, timestamp: now };
  }

  /** @inheritdoc */
  public async update(uid: UserId, id: string, data: Partial<CreateActivityDto>): Promise<Activity> {
    const doc = await this.findById(id);
    if (!doc) throw new NotFoundError('Activity', id);
    if (doc.uid !== uid) throw new AuthorizationError(`Activity:${id}`);
    await this.db.collection(this.collection).doc(id).update({
      ...data,
      updatedAt: FieldValue.serverTimestamp(),
    });
    return { ...doc, ...data };
  }

  /** @inheritdoc */
  public async delete(uid: UserId, id: string): Promise<void> {
    const doc = await this.findById(id);
    if (!doc) throw new NotFoundError('Activity', id);
    if (doc.uid !== uid) throw new AuthorizationError(`Activity:${id}`);
    await this.db.collection(this.collection).doc(id).update({
      deletedAt: FieldValue.serverTimestamp(),
    });
  }

  private buildUserQuery(uid: UserId): Query {
    return this.db.collection(this.collection)
      .where('uid', '==', uid)
      .where('deletedAt', '==', null);
  }

  private toEntity(id: string, data: FirebaseFirestore.DocumentData): Activity {
    return {
      id,
      uid: UserIdBrand(String(data['uid'] as string)),
      input: data['input'] as Activity['input'],
      emissionKg: KgCO2e(Number(data['emissionKg'])),
      timestamp: (data['timestamp'] as FirebaseFirestore.Timestamp).toDate(),
      notes: data['notes'] as string | undefined,
    };
  }
}
